insert into order_master (store_name, store_phone, method_of_order) values ('luctus et ultrices posuere cubilia', '6336434655', 'potenti cras in purus eu');
insert into order_master (store_name, store_phone, method_of_order) values ('nisi at nibh in hac habitasse', '7478701344', 'ante vivamus tortor duis mattis egestas');
insert into order_master (store_name, store_phone, method_of_order) values ('tincidunt in leo maecenas pulvinar', '9525248174', 'mauris vulputate elementum nullam varius');
insert into order_master (store_name, store_phone, method_of_order) values ('nunc vestibulum ante ipsum primis', '5843424528', 'luctus cum sociis natoque penatibus et');
insert into order_master (store_name, store_phone, method_of_order) values ('ac consequat ', '3653056321', 'tristique fusce congue diam id ornare');
insert into order_master (store_name, store_phone, method_of_order) values ('ac consequat metus sapien ut nunc', '3653056321', 'tristique fusce congue diam id ornare');
insert into order_master (store_name, store_phone, method_of_order) values ('ac consequat metus sapien ut ', '36530563', 'tristique fusce congue diam ');
insert into order_master (store_name, store_phone, method_of_order) values ('ac consequat metus sapie', '3653321', 'tristique fusce congu');
insert into order_master (store_name, store_phone, method_of_order) values ('ac consequat metu', '365321', 'tristique fusce con');
insert into order_master (store_name, store_phone, method_of_order) values ('ac consequat me', '36531', 'tristique fusce c');