/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.diviso.graeshoppe.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CancellationRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8112733879926909896L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CancellationRequest\",\"namespace\":\"com.diviso.graeshoppe.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"status\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"orderId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"paymentId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"date\",\"type\":\"long\",\"logicalType\":\"date\"},{\"name\":\"amount\",\"type\":[\"null\",\"double\"],\"default\":0.0},{\"name\":\"reference\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"cancelledOrderLine\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"CancelledOrderLine\",\"fields\":[{\"name\":\"productId\",\"type\":\"long\"},{\"name\":\"itemName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"quantity\",\"type\":\"long\"},{\"name\":\"pricePerUnit\",\"type\":\"double\"},{\"name\":\"amount\",\"type\":\"double\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CancellationRequest> ENCODER =
      new BinaryMessageEncoder<CancellationRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CancellationRequest> DECODER =
      new BinaryMessageDecoder<CancellationRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CancellationRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CancellationRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CancellationRequest>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CancellationRequest to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CancellationRequest from a ByteBuffer. */
  public static CancellationRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public java.lang.String status;
  @Deprecated public java.lang.String orderId;
  @Deprecated public java.lang.String paymentId;
  @Deprecated public long date;
  @Deprecated public java.lang.Double amount;
  @Deprecated public java.lang.String reference;
  @Deprecated public java.util.List<com.diviso.graeshoppe.avro.CancelledOrderLine> cancelledOrderLine;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CancellationRequest() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param status The new value for status
   * @param orderId The new value for orderId
   * @param paymentId The new value for paymentId
   * @param date The new value for date
   * @param amount The new value for amount
   * @param reference The new value for reference
   * @param cancelledOrderLine The new value for cancelledOrderLine
   */
  public CancellationRequest(java.lang.Long id, java.lang.String status, java.lang.String orderId, java.lang.String paymentId, java.lang.Long date, java.lang.Double amount, java.lang.String reference, java.util.List<com.diviso.graeshoppe.avro.CancelledOrderLine> cancelledOrderLine) {
    this.id = id;
    this.status = status;
    this.orderId = orderId;
    this.paymentId = paymentId;
    this.date = date;
    this.amount = amount;
    this.reference = reference;
    this.cancelledOrderLine = cancelledOrderLine;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return status;
    case 2: return orderId;
    case 3: return paymentId;
    case 4: return date;
    case 5: return amount;
    case 6: return reference;
    case 7: return cancelledOrderLine;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: status = (java.lang.String)value$; break;
    case 2: orderId = (java.lang.String)value$; break;
    case 3: paymentId = (java.lang.String)value$; break;
    case 4: date = (java.lang.Long)value$; break;
    case 5: amount = (java.lang.Double)value$; break;
    case 6: reference = (java.lang.String)value$; break;
    case 7: cancelledOrderLine = (java.util.List<com.diviso.graeshoppe.avro.CancelledOrderLine>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.String value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.String getPaymentId() {
    return paymentId;
  }

  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.String value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.Long getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.Long value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.lang.Double getAmount() {
    return amount;
  }

  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.lang.Double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'reference' field.
   * @return The value of the 'reference' field.
   */
  public java.lang.String getReference() {
    return reference;
  }

  /**
   * Sets the value of the 'reference' field.
   * @param value the value to set.
   */
  public void setReference(java.lang.String value) {
    this.reference = value;
  }

  /**
   * Gets the value of the 'cancelledOrderLine' field.
   * @return The value of the 'cancelledOrderLine' field.
   */
  public java.util.List<com.diviso.graeshoppe.avro.CancelledOrderLine> getCancelledOrderLine() {
    return cancelledOrderLine;
  }

  /**
   * Sets the value of the 'cancelledOrderLine' field.
   * @param value the value to set.
   */
  public void setCancelledOrderLine(java.util.List<com.diviso.graeshoppe.avro.CancelledOrderLine> value) {
    this.cancelledOrderLine = value;
  }

  /**
   * Creates a new CancellationRequest RecordBuilder.
   * @return A new CancellationRequest RecordBuilder
   */
  public static com.diviso.graeshoppe.avro.CancellationRequest.Builder newBuilder() {
    return new com.diviso.graeshoppe.avro.CancellationRequest.Builder();
  }

  /**
   * Creates a new CancellationRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CancellationRequest RecordBuilder
   */
  public static com.diviso.graeshoppe.avro.CancellationRequest.Builder newBuilder(com.diviso.graeshoppe.avro.CancellationRequest.Builder other) {
    return new com.diviso.graeshoppe.avro.CancellationRequest.Builder(other);
  }

  /**
   * Creates a new CancellationRequest RecordBuilder by copying an existing CancellationRequest instance.
   * @param other The existing instance to copy.
   * @return A new CancellationRequest RecordBuilder
   */
  public static com.diviso.graeshoppe.avro.CancellationRequest.Builder newBuilder(com.diviso.graeshoppe.avro.CancellationRequest other) {
    return new com.diviso.graeshoppe.avro.CancellationRequest.Builder(other);
  }

  /**
   * RecordBuilder for CancellationRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CancellationRequest>
    implements org.apache.avro.data.RecordBuilder<CancellationRequest> {

    private long id;
    private java.lang.String status;
    private java.lang.String orderId;
    private java.lang.String paymentId;
    private long date;
    private java.lang.Double amount;
    private java.lang.String reference;
    private java.util.List<com.diviso.graeshoppe.avro.CancelledOrderLine> cancelledOrderLine;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.diviso.graeshoppe.avro.CancellationRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderId)) {
        this.orderId = data().deepCopy(fields()[2].schema(), other.orderId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[3].schema(), other.paymentId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.date)) {
        this.date = data().deepCopy(fields()[4].schema(), other.date);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.amount)) {
        this.amount = data().deepCopy(fields()[5].schema(), other.amount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.reference)) {
        this.reference = data().deepCopy(fields()[6].schema(), other.reference);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.cancelledOrderLine)) {
        this.cancelledOrderLine = data().deepCopy(fields()[7].schema(), other.cancelledOrderLine);
        fieldSetFlags()[7] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CancellationRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(com.diviso.graeshoppe.avro.CancellationRequest other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderId)) {
        this.orderId = data().deepCopy(fields()[2].schema(), other.orderId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[3].schema(), other.paymentId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.date)) {
        this.date = data().deepCopy(fields()[4].schema(), other.date);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.amount)) {
        this.amount = data().deepCopy(fields()[5].schema(), other.amount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.reference)) {
        this.reference = data().deepCopy(fields()[6].schema(), other.reference);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.cancelledOrderLine)) {
        this.cancelledOrderLine = data().deepCopy(fields()[7].schema(), other.cancelledOrderLine);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.String getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder setStatus(java.lang.String value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }

    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder setOrderId(java.lang.String value) {
      validate(fields()[2], value);
      this.orderId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.String getPaymentId() {
      return paymentId;
    }

    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder setPaymentId(java.lang.String value) {
      validate(fields()[3], value);
      this.paymentId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.Long getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder setDate(long value) {
      validate(fields()[4], value);
      this.date = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder clearDate() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.lang.Double getAmount() {
      return amount;
    }

    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder setAmount(java.lang.Double value) {
      validate(fields()[5], value);
      this.amount = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'reference' field.
      * @return The value.
      */
    public java.lang.String getReference() {
      return reference;
    }

    /**
      * Sets the value of the 'reference' field.
      * @param value The value of 'reference'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder setReference(java.lang.String value) {
      validate(fields()[6], value);
      this.reference = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'reference' field has been set.
      * @return True if the 'reference' field has been set, false otherwise.
      */
    public boolean hasReference() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'reference' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder clearReference() {
      reference = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'cancelledOrderLine' field.
      * @return The value.
      */
    public java.util.List<com.diviso.graeshoppe.avro.CancelledOrderLine> getCancelledOrderLine() {
      return cancelledOrderLine;
    }

    /**
      * Sets the value of the 'cancelledOrderLine' field.
      * @param value The value of 'cancelledOrderLine'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder setCancelledOrderLine(java.util.List<com.diviso.graeshoppe.avro.CancelledOrderLine> value) {
      validate(fields()[7], value);
      this.cancelledOrderLine = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'cancelledOrderLine' field has been set.
      * @return True if the 'cancelledOrderLine' field has been set, false otherwise.
      */
    public boolean hasCancelledOrderLine() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'cancelledOrderLine' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.avro.CancellationRequest.Builder clearCancelledOrderLine() {
      cancelledOrderLine = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CancellationRequest build() {
      try {
        CancellationRequest record = new CancellationRequest();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (java.lang.String) defaultValue(fields()[1]);
        record.orderId = fieldSetFlags()[2] ? this.orderId : (java.lang.String) defaultValue(fields()[2]);
        record.paymentId = fieldSetFlags()[3] ? this.paymentId : (java.lang.String) defaultValue(fields()[3]);
        record.date = fieldSetFlags()[4] ? this.date : (java.lang.Long) defaultValue(fields()[4]);
        record.amount = fieldSetFlags()[5] ? this.amount : (java.lang.Double) defaultValue(fields()[5]);
        record.reference = fieldSetFlags()[6] ? this.reference : (java.lang.String) defaultValue(fields()[6]);
        record.cancelledOrderLine = fieldSetFlags()[7] ? this.cancelledOrderLine : (java.util.List<com.diviso.graeshoppe.avro.CancelledOrderLine>) defaultValue(fields()[7]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CancellationRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<CancellationRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CancellationRequest>
    READER$ = (org.apache.avro.io.DatumReader<CancellationRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
