/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.diviso.graeshoppe.order.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ApprovalInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6093757732553960839L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApprovalInfo\",\"namespace\":\"com.diviso.graeshoppe.order.avro\",\"fields\":[{\"name\":\"orderId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"acceptedAt\",\"type\":\"long\",\"logicalType\":\"date\"},{\"name\":\"expectedDelivery\",\"type\":\"long\",\"default\":0,\"logicalType\":\"date\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ApprovalInfo> ENCODER =
      new BinaryMessageEncoder<ApprovalInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ApprovalInfo> DECODER =
      new BinaryMessageDecoder<ApprovalInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ApprovalInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ApprovalInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ApprovalInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ApprovalInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ApprovalInfo from a ByteBuffer. */
  public static ApprovalInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String orderId;
  @Deprecated public long acceptedAt;
  @Deprecated public long expectedDelivery;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApprovalInfo() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param acceptedAt The new value for acceptedAt
   * @param expectedDelivery The new value for expectedDelivery
   */
  public ApprovalInfo(java.lang.String orderId, java.lang.Long acceptedAt, java.lang.Long expectedDelivery) {
    this.orderId = orderId;
    this.acceptedAt = acceptedAt;
    this.expectedDelivery = expectedDelivery;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return acceptedAt;
    case 2: return expectedDelivery;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.String)value$; break;
    case 1: acceptedAt = (java.lang.Long)value$; break;
    case 2: expectedDelivery = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'acceptedAt' field.
   * @return The value of the 'acceptedAt' field.
   */
  public java.lang.Long getAcceptedAt() {
    return acceptedAt;
  }

  /**
   * Sets the value of the 'acceptedAt' field.
   * @param value the value to set.
   */
  public void setAcceptedAt(java.lang.Long value) {
    this.acceptedAt = value;
  }

  /**
   * Gets the value of the 'expectedDelivery' field.
   * @return The value of the 'expectedDelivery' field.
   */
  public java.lang.Long getExpectedDelivery() {
    return expectedDelivery;
  }

  /**
   * Sets the value of the 'expectedDelivery' field.
   * @param value the value to set.
   */
  public void setExpectedDelivery(java.lang.Long value) {
    this.expectedDelivery = value;
  }

  /**
   * Creates a new ApprovalInfo RecordBuilder.
   * @return A new ApprovalInfo RecordBuilder
   */
  public static com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder newBuilder() {
    return new com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder();
  }

  /**
   * Creates a new ApprovalInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApprovalInfo RecordBuilder
   */
  public static com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder newBuilder(com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder other) {
    return new com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder(other);
  }

  /**
   * Creates a new ApprovalInfo RecordBuilder by copying an existing ApprovalInfo instance.
   * @param other The existing instance to copy.
   * @return A new ApprovalInfo RecordBuilder
   */
  public static com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder newBuilder(com.diviso.graeshoppe.order.avro.ApprovalInfo other) {
    return new com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder(other);
  }

  /**
   * RecordBuilder for ApprovalInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApprovalInfo>
    implements org.apache.avro.data.RecordBuilder<ApprovalInfo> {

    private java.lang.String orderId;
    private long acceptedAt;
    private long expectedDelivery;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.acceptedAt)) {
        this.acceptedAt = data().deepCopy(fields()[1].schema(), other.acceptedAt);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.expectedDelivery)) {
        this.expectedDelivery = data().deepCopy(fields()[2].schema(), other.expectedDelivery);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ApprovalInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.diviso.graeshoppe.order.avro.ApprovalInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.acceptedAt)) {
        this.acceptedAt = data().deepCopy(fields()[1].schema(), other.acceptedAt);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.expectedDelivery)) {
        this.expectedDelivery = data().deepCopy(fields()[2].schema(), other.expectedDelivery);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }

    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder setOrderId(java.lang.String value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'acceptedAt' field.
      * @return The value.
      */
    public java.lang.Long getAcceptedAt() {
      return acceptedAt;
    }

    /**
      * Sets the value of the 'acceptedAt' field.
      * @param value The value of 'acceptedAt'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder setAcceptedAt(long value) {
      validate(fields()[1], value);
      this.acceptedAt = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'acceptedAt' field has been set.
      * @return True if the 'acceptedAt' field has been set, false otherwise.
      */
    public boolean hasAcceptedAt() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'acceptedAt' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder clearAcceptedAt() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'expectedDelivery' field.
      * @return The value.
      */
    public java.lang.Long getExpectedDelivery() {
      return expectedDelivery;
    }

    /**
      * Sets the value of the 'expectedDelivery' field.
      * @param value The value of 'expectedDelivery'.
      * @return This builder.
      */
    public com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder setExpectedDelivery(long value) {
      validate(fields()[2], value);
      this.expectedDelivery = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'expectedDelivery' field has been set.
      * @return True if the 'expectedDelivery' field has been set, false otherwise.
      */
    public boolean hasExpectedDelivery() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'expectedDelivery' field.
      * @return This builder.
      */
    public com.diviso.graeshoppe.order.avro.ApprovalInfo.Builder clearExpectedDelivery() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ApprovalInfo build() {
      try {
        ApprovalInfo record = new ApprovalInfo();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.String) defaultValue(fields()[0]);
        record.acceptedAt = fieldSetFlags()[1] ? this.acceptedAt : (java.lang.Long) defaultValue(fields()[1]);
        record.expectedDelivery = fieldSetFlags()[2] ? this.expectedDelivery : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ApprovalInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<ApprovalInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ApprovalInfo>
    READER$ = (org.apache.avro.io.DatumReader<ApprovalInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
